{{- if .Values.notification.email.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doctorlib-navigator.fullname" . }}-smtp
  labels:
    {{- include "doctorlib-navigator.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-username: {{ .Values.notification.email.username | quote }}
  smtp-password: {{ .Values.notification.email.password | quote }}
{{- end }}
